on: 
   issues:
    types: [opened]

jobs:
  artia-create-activity-job:
    runs-on: ubuntu-latest
    name: Create Activity.
    steps:
      - name: Criando Atividade
        id: Create
        uses: mobral-inc/criar-atividade-por-issue@v1.0.0
        with: 
          organizationId: 53257
          accountId: 1830068
          folderId: 2170379
          creatorEmail: 'bot.artia@gmail.com'
          creatorPassword: ${{ secrets.ARTIA_PASSWORD }}
      
