# This is a basic workflow to help you get started with Actions

name: pull_request_closed

  
on:
  pull_request:
    branches: 
      - main
    types: [closed]

  
jobs:
  artia_comment_job:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    name: Comment Activity.
    steps:
      - name: Comentando Atividade
        id: comment
        uses: mobral-inc/criar-comentario-por-pull-request@v1.0.0
        with: 
          organizationId: 111402
          accountId: 3757321
          creatorEmail: 'nerdplis@gmail.com'
          creatorPassword: ${{ secrets.ARTIA_PASSWORD }}
      
