# This is a basic workflow to help you get started with Actions

name: pull_request_closed

  
on:
  pull_request:
    branches: 
      - main
    types: [closed]
  
jobs:
  artia_comment_job:
    runs-on: ubuntu-latest
    name: Comment Activity.
    steps:
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          WHO_TO_TRUST: ${{ secrets.ARTIA_PASSWORD }}
        if:  env.WHO_TO_TRUST == 'mobralzera'
        run: echo "I know what the password is!"
